apiVersion : apps/v1
kind: Deployment
metadata:
  name: bacnkend-sword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacnkend-sword
  template:
    metadata:
      labels:
        app: bacnkend-sword
    spec:
      containers:
      - image: gcr.io/fillcraft-swards/backend_swards_img:latest
        imagePullPolicy: Always
        name: bacnkend-sword
        ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
    name: bacnkend-sword
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
    selector:
        app: bacnkend-sword
---

